### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by mlienau**
Fix link to Travis CI link badge. Added hook source code and some more examples.

### CODE REVIEW

**Comment by mlienau** [comment]
Is this able to be merged in? Or can I haz write access please?

**Comment by paulirwin** [comment]
@captray-zz @captray needs to figure out how to regain access to his repo :-) I don't have access either.

**Comment by paulirwin** [comment]
Oh it looks like I can merge this though, I just can't add you

**Comment by captray** [comment]
Great.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
